### ISSUE TITLE
issue launching robot.sh on ev3

### ISSUE THREAD

**Issue by jmller** [tum-lkn/NCSbench#1]
Hello!
I've got a problem launching the robot.sh on my ev3.
The used operating system is the last debian Jessie image (brickman v0.8.1) and when I try launching the robot.sh it just returns me the following error: 
![image](https://user-images.githubusercontent.com/59137856/76319205-2965fc00-62df-11ea-9704-2be599905065.png)

Do you have any suggestions for solving this issue?
Thanks in advance!

**Comment by szoppi** [comment]
Hi Jmller,

Thanks for spotting the bug. 

`import controller_params.py` should solve the issue.
